
name: CI
#Running tests on all branches
on: [push,pull_request]

jobs:  
  # This is a job for running ci tests on linux python3
  linux-build:
      runs-on: [ubuntu-18.04]
    
      container:
          image: 'rootproject/root:latest'
      steps:
        - uses: actions/checkout@v2
    # The type of runner that the job will run on
        - name: Test with pytest
          env:
            COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          run: |
            yum install -y python-pip ghostscript 
            pip install pytest
            python setup.py test
            pip install coveralls
            coveralls